server:
  port: 80
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.liuxc.restful.domain
  mapper-locations: classpath:mybatis/mapper/**.xml
  
spring:
  messages:
    basename: message
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      master:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/master?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false
        username: liuxc
        password: liuxc
        minIdle: 5                                          #配置连接池最小连接数
        initialSize: 5                                      #配置连接池初始化连接数
        maxActive: 12                                       #配置连接池最大连接数
        maxWait: 60000                                      #配置获取连接等待超时的时间
        poolPreparedStatements: true                        #打开PSCache，并且指定每个连接上PSCache的大小 
        maxPoolPreparedStatementPerConnectionSize: 20
        validationQuery: select 1 from dual                 #用来检测连接是否有效的sql，要求是一个查询语句。 如果validationQuery为null，testOnBorrow、testOnReturn、 testWhileIdle都不会其作用。
        testOnBorrow: false                                 #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        testOnReturn: false                                 #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
        testWhileIdle: true                                 #建议配置为true，不影响性能，并且保证安全性。 申请连接的时候检测，如果空闲时间大于 timeBetweenEvictionRunsMillis， 执行validationQuery检测连接是否有效。
        timeBetweenEvictionRunsMillis: 60000                # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis: 100000                  # 配置一个连接在池中最小生存的时间，单位是毫秒
        filters: stat,wall,log4j                            #druid监控过滤器操作
        useGlobalDataSourceStat: true
      slave:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/slave?useUnicode=true&amp;characterEncoding=UTF-8&useSSL=false
        username: liuxc
        password: liuxc
        minIdle: 5                                          #配置连接池最小连接数
        initialSize: 5                                      #配置连接池初始化连接数
        maxActive: 12                                        #配置连接池最大连接数
        maxWait: 60000                               #配置最大超时断开时间
        poolPreparedStatements: true                         # 打开PSCache，并且指定每个连接上PSCache的大小 
        maxPoolPreparedStatementPerConnectionSize: 20
        validationQuery: select 1 from dual                 #用来检测连接是否有效的sql，要求是一个查询语句。 如果validationQuery为null，testOnBorrow、testOnReturn、 testWhileIdle都不会其作用。
        testOnBorrow: false                                 #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        testOnReturn: false                                 #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
        testWhileIdle: true                                 #建议配置为true，不影响性能，并且保证安全性。 申请连接的时候检测，如果空闲时间大于 timeBetweenEvictionRunsMillis， 执行validationQuery检测连接是否有效。
        timeBetweenEvictionRunsMillis: 60000                # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis: 100000                  # 配置一个连接在池中最小生存的时间，单位是毫秒
        filters: stat,wall,log4j                            #druid监控过滤器操作
        useGlobalDataSourceStat: true
      web-stat-filter:                   # WebStatFilter配置
        url-pattern: /*
        enabled: true
        exclusions: /druid/*,*.gif,*.jpg,*.png,*.css,*.ico,*.js
      stat-view-servlet:                 # StatViewServlet
        enabled: true
        url-pattern: /druid/*
        reset-enable: false               #是否能够重置数据
        login-username: admin             #登陆用户名
        login-password: admin             #登陆密码
        allow: 127.0.0.1                  #白名单
        deny:                             #黑名单
      aop-patterns: com.liuxc.restful.service.* #配置spring监控

      
        
        